### PR TITLE
feat(hpack): proper implementation based on twitter hpack

### PR DESCRIPTION
**Pull request by antmat**
Here is an implementation of cocaine HPACK for java-framework (common to the one used in cocaine-core).
I didn't tested it though, so right now it's just to review the idea.
It also lacks convient methods to work wit a list of headers right now.

@akirakozov @vapolyakov PTAL

### CODE REVIEW

**Comment by vapolyakov** [comment]
Manually merged, refactored and tested, it works definitely not worse than previous version.

https://github.com/akirakozov/cocaine-framework-java/commit/fbab823732ae76a56a3569243891db0146088aa3
https://github.com/akirakozov/cocaine-framework-java/commit/9d3237fc3aebc2c05a22b76ef1fb2d19841076cc
https://github.com/akirakozov/cocaine-framework-java/commit/9d3237fc3aebc2c05a22b76ef1fb2d19841076cc

**Comment by antmat** [comment]
cool! sorry for the dirty code

**Comment by valp124** [comment]
Somehow you guys have been unwittingly forwarding this to me, not sure how my email address got there. Although I'm also V.A. Polyakov, so it's easy to get confused ;)

**Comment by akirakozov** [comment]
Hi, there are one more vpolyakov in our watchers list: https://github.com/akirakozov/cocaine-framework-java/watchers. Could it be your another account with same email?)

**Comment by ghost** [comment]
Yep, that seems to be it. I wasn't even aware of that account. Nor have any idea how it ended up watching your project. Anyway, thanks a lot for figuring it out!

**Pull request closed without merging**
